# Generated by Selenium IDE
require 'selenium-webdriver'
require 'json'
describe 'FirefoxSelenium' do
  before(:each) do
    @driver = Selenium::WebDriver.for :firefox
    @vars = {}
  end
  after(:each) do
    @driver.quit
  end
  it 'firefoxSelenium' do
    @driver.get('https://www.google.es/')
    @driver.manage.resize_to(550, 691)
    @driver.find_element(:id, 'APjFqb').click
    @driver.find_element(:id, 'APjFqb').send_keys('traslado de pianos')
    @driver.find_element(:css, '.QCzoEc > svg').click
    @driver.find_element(:name, 'btnK').click
    @driver.find_element(:css, '.uEierd:nth-child(3) .v5yQqb').click
    @driver.execute_script("window.scrollTo(0,59)")
    @driver.find_element(:css, '#tads > .uEierd:nth-child(3) .CCgQ5 > span').click
    @driver.execute_script("window.scrollTo(0,59)")
    @driver.get('https://www.google.es/')
    @driver.find_element(:id, 'APjFqb').click
    @driver.find_element(:id, 'APjFqb').send_keys('traslado de pianos')
    @driver.find_element(:css, '.QCzoEc > svg').click
    @driver.find_element(:name, 'btnK').click
    @driver.find_element(:css, '#tads > .uEierd:nth-child(3) .CCgQ5 > span').click
    @driver.execute_script("window.scrollTo(0,59)")
    @driver.close
  end
end
