// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class FirefoxSeleniumTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void firefoxSelenium() {
    driver.get("https://www.google.es/");
    driver.manage().window().setSize(new Dimension(550, 691));
    driver.findElement(By.id("APjFqb")).click();
    driver.findElement(By.id("APjFqb")).sendKeys("traslado de pianos");
    driver.findElement(By.cssSelector(".QCzoEc > svg")).click();
    driver.findElement(By.name("btnK")).click();
    driver.findElement(By.cssSelector(".uEierd:nth-child(3) .v5yQqb")).click();
    js.executeScript("window.scrollTo(0,59)");
    driver.findElement(By.cssSelector("#tads > .uEierd:nth-child(3) .CCgQ5 > span")).click();
    js.executeScript("window.scrollTo(0,59)");
    driver.get("https://www.google.es/");
    driver.findElement(By.id("APjFqb")).click();
    driver.findElement(By.id("APjFqb")).sendKeys("traslado de pianos");
    driver.findElement(By.cssSelector(".QCzoEc > svg")).click();
    driver.findElement(By.name("btnK")).click();
    driver.findElement(By.cssSelector("#tads > .uEierd:nth-child(3) .CCgQ5 > span")).click();
    js.executeScript("window.scrollTo(0,59)");
    driver.close();
  }
}
