// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Firefox-Selenium', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Firefox-Selenium', async function() {
    await driver.get("https://www.google.es/")
    await driver.manage().window().setRect({ width: 550, height: 691 })
    await driver.findElement(By.id("APjFqb")).click()
    await driver.findElement(By.id("APjFqb")).sendKeys("traslado de pianos")
    await driver.findElement(By.css(".QCzoEc > svg")).click()
    await driver.findElement(By.name("btnK")).click()
    await driver.findElement(By.css(".uEierd:nth-child(3) .v5yQqb")).click()
    await driver.executeScript("window.scrollTo(0,59)")
    await driver.findElement(By.css("#tads > .uEierd:nth-child(3) .CCgQ5 > span")).click()
    await driver.executeScript("window.scrollTo(0,59)")
    await driver.get("https://www.google.es/")
    await driver.findElement(By.id("APjFqb")).click()
    await driver.findElement(By.id("APjFqb")).sendKeys("traslado de pianos")
    await driver.findElement(By.css(".QCzoEc > svg")).click()
    await driver.findElement(By.name("btnK")).click()
    await driver.findElement(By.css("#tads > .uEierd:nth-child(3) .CCgQ5 > span")).click()
    await driver.executeScript("window.scrollTo(0,59)")
    await driver.close()
  })
})
