# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestFirefoxSelenium1():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_firefoxSelenium1(self):
    self.driver.get("https://www.google.es/")
    self.driver.set_window_size(550, 691)
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.ID, "APjFqb").send_keys("traslado de pianos")
    self.driver.find_element(By.CSS_SELECTOR, ".QCzoEc > svg").click()
    self.driver.find_element(By.NAME, "btnK").click()
    self.driver.find_element(By.CSS_SELECTOR, ".uEierd:nth-child(3) .v5yQqb").click()
    self.driver.execute_script("window.scrollTo(0,59)")
    self.driver.find_element(By.CSS_SELECTOR, "#tads > .uEierd:nth-child(3) .CCgQ5 > span").click()
    self.driver.execute_script("window.scrollTo(0,59)")
    self.driver.get("https://www.google.es/")
    self.driver.find_element(By.ID, "APjFqb").click()
    self.driver.find_element(By.ID, "APjFqb").send_keys("traslado de pianos")
    self.driver.find_element(By.CSS_SELECTOR, ".QCzoEc > svg").click()
    self.driver.find_element(By.NAME, "btnK").click()
    self.driver.find_element(By.CSS_SELECTOR, "#tads > .uEierd:nth-child(3) .CCgQ5 > span").click()
    self.driver.execute_script("window.scrollTo(0,59)")
    self.driver.close()
  
